include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  rules:
    - arguments-ordering:
        child-last: true
    - avoid-banned-imports: false

linter:
  rules:
     avoid_print: true
     prefer_single_quotes: true
