name: personal_portfolio_web_app
description: Portolio of Md Didarul.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+2

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.10.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.4
  dart_code_metrics_presets: ^1.8.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avatar.jpg
